openapi: 3.0.3
info:
  title: Personal Budgeting API
  description: API per la gestione di un sistema di budgeting personale con dashboard.
  version: 1.0.0

servers:
  - url: https://api.budgetapp.com/v1

paths: 

  /dashboard:
    get:
      summary: Dati dashboard mensile
      security:
        - bearerAuth: []
      parameters:
        - name: month
          in: query
          required: true
          schema:
            type: string
            example: "2025-02"
      responses:
        '200':
          description: Dati aggregati per la dashboard
          content:
            application/json:
              schema:
                type: object
                properties:
                  monthly_total_budget:
                    type: number
                    description: totale pianificato di aver speso nel budget
                  monthly_total_spent:
                    type: number
                    description: totale speso nel mese passato per parametro
                  annual_months:
                    type: array
                    description: lista di mesi con realativi importi totali spesi
                    items:
                      type: object
                      properties:
                        month:
                          type: string
                          example: "2025-02"
                        amount:
                          type: number
                          example: 1500.75
                  best_month_of_year:
                    type: string
                    descritpion: mese migliore dell'anno calcolato come il mese dove la differenza tra total_budget e total_spent è maggiore
                    example: "2025-04"
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/CategorySummary'

  /categories:
    get:
      summary: Elenco categorie utente
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista categorie
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

    post:
      summary: Aggiungi nuova categoria
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - goal
              properties:
                name:
                  type: string
                goal:
                  type: number 
      responses:
        '201':
          description: Categoria creata

  /expenses:
    get:
      summary: Elenco spese
      security:
        - bearerAuth: []
      parameters:
        - name: month
          in: query
          schema:
            type: string
            example: "2025-06"
      responses:
        '200':
          description: Lista spese filtrata per mese
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Expense'

    post:
      summary: Aggiungi spesa
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Expense'
      responses:
        '201':
          description: Spesa aggiunta

  /budget:
    get:
      summary: Ottieni budget mensile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Valori di budget
          content:
            application/json:
              schema:
                type: object
                properties:
                  month:
                    type: string
                  totalBudget:
                    type: number
                  categoryBudgets:
                    type: array
                    items:
                      $ref: '#/components/schemas/CategoryBudget'

    post:
      summary: Imposta budget mensile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                month:
                  type: string
                  example: "2025-06"
                totalBudget:
                  type: number
                categoryBudgets:
                  type: array
                  items:
                    $ref: '#/components/schemas/CategoryBudget'
      responses:
        '200':
          description: Budget aggiornato

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Category:
      type: object
      required: [name]
      properties:
        id:
          type: number
        name:
          type: string
        goal:
          type: number

    CategorySummary:
      type: object
      properties:
        name:
          type: string
        spent:
          type: number
        goal:
          type: number

    Expense:
      type: object
      required: [amount, categoryId, date]
      properties:
        id:
          type: number
        amount:
          type: number
        categoryId:
          type: number
        description:
          type: string
        date:
          type: string
          format: date

    CategoryBudget:
      type: object
      required: [categoryId, amount]
      properties:
        categoryId:
          type: number
        amount:
          type: number
