spring:
  application:
    name: budgeting-api
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

supabase:
  url: https://sjkuqvemdhdoicqimnrw.supabase.co
  secret-key: sb_secret_Le4XEYkCenRh2aIG20cjoA_Wv6tLkor
  publishable-key: sb_publishable_Fx4p4gZo2cHgG6lx9zJ1Xw_xEONaXDC
  jwks-url: https://sjkuqvemdhdoicqimnrw.supabase.co/auth/v1/.well-known/jwks.json
  test-user-email: testuser-8d94f1a2c7@example.com
  test-user-password: X$7gP!rZ9qMv#4Kt
  test-user-id: 2062a062-39aa-4709-87c5-e7b97ce5ffd2